"""add_is_email_verified_to_users

Revision ID: 20d250bea784
Revises: 6fc915cac3e1
Create Date: 2026-05-06 17:51:41.406214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20d250bea784'
down_revision: Union[str, None] = '6fc915cac3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
