"""add_images_to_wish_items

Revision ID: 2b85e80489b2
Revises: 87b9897b317e
Create Date: 2026-05-12 10:14:00.319077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b85e80489b2'
down_revision: Union[str, None] = '87b9897b317e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_items', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish_items', 'images')
    # ### end Alembic commands ###
