"""add_is_fulfilled_to_reservations

Revision ID: 5851f6600c2b
Revises: b7c3d8e1f204
Create Date: 2026-05-10 19:23:17.100552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5851f6600c2b'
down_revision: Union[str, None] = 'b7c3d8e1f204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('is_fulfilled', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'is_fulfilled')
    # ### end Alembic commands ###
