"""add_anon_token_to_reservations

Revision ID: 87b9897b317e
Revises: 7a8b6a93b55d
Create Date: 2026-05-10 20:38:41.858307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87b9897b317e'
down_revision: Union[str, None] = '7a8b6a93b55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('anon_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_reservations_anon_token'), 'reservations', ['anon_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_anon_token'), table_name='reservations')
    op.drop_column('reservations', 'anon_token')
    # ### end Alembic commands ###
