"""add_visibility_event_date_reservation_mode_wishlist_invites

Revision ID: a93d6fede7da
Revises: 20d250bea784
Create Date: 2026-05-07 18:31:05.747316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a93d6fede7da'
down_revision: Union[str, None] = '20d250bea784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_invites',
    sa.Column('wishlist_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('invited_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wishlist_id', 'email', name='uq_wishlist_invites_wishlist_id_email')
    )
    op.create_index(op.f('ix_wishlist_invites_wishlist_id'), 'wishlist_invites', ['wishlist_id'], unique=False)
    op.add_column('wishlists', sa.Column('event_date', sa.Date(), nullable=True))
    op.add_column('wishlists', sa.Column('visibility', sa.Enum('public', 'link_only', 'private', name='wishlistvisibility', native_enum=False), server_default='link_only', nullable=False))
    op.add_column('wishlists', sa.Column('reservation_mode', sa.Enum('anonymous', 'registered_only', name='reservationmode', native_enum=False), server_default='anonymous', nullable=False))
    op.drop_column('wishlists', 'is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('wishlists', 'reservation_mode')
    op.drop_column('wishlists', 'visibility')
    op.drop_column('wishlists', 'event_date')
    op.drop_index(op.f('ix_wishlist_invites_wishlist_id'), table_name='wishlist_invites')
    op.drop_table('wishlist_invites')
    # ### end Alembic commands ###
