"""add_store_domain_to_wish_items

Revision ID: c88bcb93f34b
Revises: 5851f6600c2b
Create Date: 2026-05-10 19:24:13.580933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c88bcb93f34b'
down_revision: Union[str, None] = '5851f6600c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_items', sa.Column('store_domain', sa.String(), nullable=True))
    op.create_index(op.f('ix_wish_items_store_domain'), 'wish_items', ['store_domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wish_items_store_domain'), table_name='wish_items')
    op.drop_column('wish_items', 'store_domain')
    # ### end Alembic commands ###
