FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml ./

RUN python3 -c "import tomllib,subprocess; f=open('pyproject.toml','rb'); d=tomllib.load(f); f.close(); subprocess.run(['uv','pip','install','--system']+d['project']['dependencies'],check=True)"

COPY . .

ENV PYTHONPATH=/app

RUN chmod +x start.sh

CMD ["./start.sh"]
